export enum screenKey {
  signIn = "signIn",
  signUp = "signUp",
  otp = "otp",
  forgotPassword = "forgotPassword",
}

export enum FirebaseErrorCode {
  "auth/invalid-phone-number" = "Số điện thoại không hợp lệ",
  "auth/missing-verification-code" = "Mã OTP không hợp lệ",
  "auth/invalid-verification-code" = "Mã OTP không hợp lệ",
  "auth/code-expired" = "Mã OTP đã hết hạn",
  "auth/credential-already-in-use" = "Số điện thoại đã được sử dụng",
  "auth/phone-number-already-exists" = "Số điện thoại đã được sử dụng",
  "auth/user-not-found" = "Người dùng không tồn tại",
  "auth/wrong-password" = "Mật khẩu không đúng",
  "auth/too-many-requests" = "Quá nhiều yêu cầu",
  "auth/network-request-failed" = "Lỗi mạng",
  "auth/user-disabled" = "Tài khoản đã bị vô hiệu hóa",
  "auth/email-already-in-use" = "Email đã được sử dụng",
  "auth/weak-password" = "Mật khẩu quá yếu",
  "auth/invalid-email" = "Email không hợp lệ",
  "auth/operation-not-allowed" = "Tính năng không được hỗ trợ",
  "auth/invalid-credential" = "Thông tin không hợp lệ",
  "auth/invalid-verification-id" = "Mã xác thực không hợp lệ",
  "auth/app-deleted" = "Ứng dụng đã bị xóa",
  "auth/app-not-authorized" = "Ứng dụng không được ủy quyền",
  "auth/argument-error" = "Lỗi đối số",
  "auth/invalid-continue-uri" = "URI không hợp lệ",
  "auth/invalid-cordova-configuration" = "Cấu hình Cordova không hợp lệ",
  "auth/invalid-custom-token" = "Token không hợp lệ",
  "auth/invalid-email-verified" = "Email đã được xác minh",
  "auth/invalid-id-token" = "Token không hợp lệ",
  "auth/invalid-tenant-id" = "ID đơn vị không hợp lệ",
  "auth/operation-not-supported-in-this-environment" = "Tính năng không được hỗ trợ trong môi trường này",
  "auth/popup-blocked" = "Popup bị chặn",
  "auth/popup-closed-by-user" = "Popup bị đóng bởi người dùng",
  "auth/unauthorized-domain" = "Domain không được ủy quyền",
  "auth/user-token-expired" = "Token người dùng đã hết hạn",
  "auth/web-storage-unsupported" = "Trình duyệt không hỗ trợ lưu trữ",
  "auth/invalid-claims" = "Thông tin không hợp lệ",
  "auth/claims-too-large" = "Thông tin quá lớn",
  "auth/id-token-expired" = "Token đã hết hạn",
  "auth/id-token-revoked" = "Token đã bị thu hồi",
  "auth/insufficient-permission" = "Không đủ quyền",
  "auth/internal-error" = "Lỗi nội bộ",
}
