export const specialtyData = [
    { label: "Nội tổng quát", value: "Nội tổng quát" },
    { label: "Tiêu hóa", value: "Tiêu hóa" },
    { label: "Thần Kinh", value: "Thần Kinh" },
    { label: "Sản phụ khoa", value: "Sản phụ khoa" },
    { label: "Nhi", value: "Nhi" },
    { label: "Hỗ trợ sinh sản", value: "Hỗ trợ sinh sản" },
    { label: "Tim mạch", value: "Tim mạch" },
    { label: "Nội tiết", value: "Nội tiết" },
    { label: "Sơ sinh", value: "Sơ sinh" },
    { label: "Răng hàm mặt", value: "Răng hàm mặt" },
    { label: "Mắt", value: "Mắt" },
    { label: "Cơ xương khớp", value: "Cơ xương khớp" },
    { label: "Tai mũi họng", value: "Tai mũi họng" },
    { label: "Dinh dưỡng", value: "Dinh dưỡng" },
    { label: "Tiết niệu", value: "Tiết niệu" },
    { label: "Ung bướu", value: "Ung bướu" },
    { label: "Phục hồi chức năng", value: "Phục hồi chức năng" },
    { label: "Ngoại tim mạch", value: "Ngoại tim mạch" },
    { label: "Da liễu", value: "Da liễu" },
    { label: "Nội thận", value: "Nội thận" },
    { label: "Thần kinh cột sống", value: "Thần kinh cột sống" },
    { label: "Ngoại thần kinh", value: "Ngoại thần kinh" },
    { label: "Ngoại vú", value: "Ngoại vú" },
    { label: "Ngoại tổng quát", value: "Ngoại tổng quát" },
    { label: "Chấn thương chỉnh hình", value: "Chấn thương chỉnh hình" },
    { label: "Miễn dịch học lâm sàng", value: "Miễn dịch học lâm sàng" },
    { label: "Điều trị béo phì", value: "Điều trị béo phì" },
    { label: "Tâm thần", value: "Tâm thần" },
    { label: "Nam học", value: "Nam học" },
    { label: "Ngoại nhi", value: "Ngoại nhi" },
    { label: "Y học bào thai", value: "Y học bào thai" },
];